name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js e Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/react/package-lock.json  
      
      - name: Instalar dependências
        working-directory: ./frontend/react
        #run: npm install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend/react
          start: npm run dev
          wait-on: 'http://localhost:5173'
        env:
          VITE_RPC_URL: ${{ secrets.VITE_RPC_URL }}
          VITE_CONTRACT_ADDRESS: ${{ secrets.VITE_CONTRACT_ADDRESS }}
          VITE_TOKEN_ADDRESS: ${{ secrets.VITE_TOKEN_ADDRESS }}

      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/react/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: cypress-videos
          path: frontend/react/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`  