name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js e Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/react/package-lock.json  
      
      - name: Instalar dependências
        working-directory: ./frontend/react
        #run: npm install
        run: |
          rm -rf node_modules package-lock.json
          npm install
          
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend/react
          start: npm run dev
          wait-on: 'http://localhost:5173'